### PR TITLE
* Changed "/json.htm" absolute URLs to relative to work with proxy path rewrites

### PR DESCRIPTION
**Pull request by mattlogic**
Similar to previous instances of absolute paths that work fine with typical Domoticz installs, but cause problems when Domoticz is behind a proxy server that rewrites the path from eg "192.168.1.100:8080/#/Dashboard" to be "192.168.1.100/domoticz/#/Dashboard"

### CODE REVIEW

**Comment by EdddieN** [comment]
Thanks @mattlogic 

@DewGew & @landaisbenj I'm merging this to the master, not sure how to roll back the changes to your branches including the beta?

The issue only happens when using proxies

**Comment by DewGew** [comment]
Is this already fixed in beta?

**Comment by EdddieN** [comment]
No, was merged directly onto master.

Also there's one for the dark theme that cannot find... if we find it we'll try to do the next merge to both beta and master (only affects behind proxy anyway)

**Comment by DewGew** [comment]
Try to change var CSSfile to
`var CSSfile = "../acttheme/css/" + files[i] + "?" + themeName;`

**Comment by EdddieN** [comment]
This?
https://github.com/EdddieN/machinon-domoticz_theme/commit/afa45b470e7d1c242c6dfbbf7c2084f4f49671b7#diff-ece786b9e8fb32d5d6c313d08a1c1db8

**Comment by DewGew** [comment]
You're too fast for me :)

**Pull request merged**
