### PR TITLE
Added search function

### PR DESCRIPTION
**Pull request by DewGew**
Added search "device name" function

search

### CODE REVIEW

**Comment by landaisbenj** [comment]
Really !!!!! Impress I am close to this

**Comment by DewGew** [comment]
Yours might be better then mine.. ;)

**Comment by EdddieN** [comment]
oh my oh my!! Can't believe you managed to pull this one off. Well done!! Really impressed!

**Comment by landaisbenj** [comment]
DewGew i've an idea. Have you put room on search input ? it can be a good stuff to suppress room span on bannav....

**Comment by EdddieN** [comment]
Is there an special instruction to get this to work?

I can see something happening when I start typing on the search box, but no filtering happens

**Comment by landaisbenj** [comment]
Yes me too. Maybe:
```
VM1318:72 Uncaught ReferenceError: log is not defined
    at searchFunction (<anonymous>:72:4)
    at HTMLInputElement.onkeyup ((index):1)
searchFunction @ VM1318:72
onkeyup @ (index):1

```

**Comment by DewGew** [comment]
I check this..

**Comment by DewGew** [comment]
I forgot to delete my debug log function :) now its fixed #61

**Comment by landaisbenj** [comment]
No don't work. it's because you hide table and no item. You must to hide item.

**Comment by DewGew** [comment]
This Fault is fixed:
VM1318:72 Uncaught ReferenceError: log is not defined
    at searchFunction (<anonymous>:72:4)
    at HTMLInputElement.onkeyup ((index):1)
searchFunction @ VM1318:72
onkeyup @ (index):1

Function log dont exist

**Comment by landaisbenj** [comment]
yes sorry i would talking about this :
https://github.com/EdddieN/machinon-domoticz_theme/pull/61#issuecomment-418275759

**Pull request merged**
