### PR TITLE
Custom logo on login page

### PR DESCRIPTION
**Pull request by DewGew**

### CODE REVIEW

**Comment by EdddieN** [comment]
Does not seem to work for me but will try later again from a different external computer, it may be caching...

**Comment by EdddieN** [comment]
Ok, tested and it does not show the custom logo. Could it be that because is a different browser (and the theme seems to operate per browser settings) is not loading the custom logo?

**Comment by DewGew** [comment]
its working for me on chrome and on edge

**Comment by EdddieN** [comment]
But are you using a different browser than the one you used to setup the custom logo?

if I remember well, the theme settings are individual per browser, correct?

This is what I have done:
1.- Computer 1 set custom logo
2.- Use computer 2 (brand new session) outside LAN to access DZ, it showed default logo

**Comment by DewGew** [comment]
Its saves only in the browser

**Comment by EdddieN** [comment]
ok, so if I use a different browser then it won't know. cookies right?

A browser cannot write to the web server folder (unless it has a PHP script) Is it worth looking into this?

Or alternatively being able to copy the "cookie settings" to the style/folder so DZ remembers?
Or maybe we just forget, I think the browser selection is good. However there're certain settings that would be better being global. 

That said, my experience with Domoticz and PHP out of the box (ie no Nginx) has not been great...

**Comment by EdddieN** [comment]
That would mean the same settings for all the browsers. I like what you have done that you have multiple settings per device.

Since the customLogo needs to be uploaded to the www/sytels/... folder, maybe worth having a json default config there when the custom are not found on the cookies?

Or as you say, have an option for settings to make them global and these are stored as user variables? Just wondering what would be the less confusing way for a user.

**Comment by DewGew** [comment]
default setting is empty. IF there is nothing set in settings it Will be default logo eg machinon. So IF the user wants same settings on all devices he just have to change theme.json.

**Pull request merged**
