### PR TITLE
Added isMobile variable

### PR DESCRIPTION
**Pull request by DewGew**
observer messed up dashboard on mobile devices so observer is disabled when isMobile is true.

### CODE REVIEW

**Comment by landaisbenj** [comment]
oO o yes fine with switch but not with dash ?:/

**Comment by DewGew** [comment]
@landaisbenj @EdddieN is this needed?

**Comment by landaisbenj** [comment]
Observer can be a great help for other feature. We can disable it, but i think we must to find why it messed up dashboard. Reason can be found in the futur. 
Observer make flex more global. No needed css media different for smartphone laptop or tv...

**Comment by DewGew** [comment]
We skip this for now..

**Pull request closed without merging**
