### PR TITLE
Css grid layout + cleanup + fix for mobile dashboard

### PR DESCRIPTION
**Pull request by davidlb**

### CODE REVIEW

**Comment by davidlb** [comment]
There is one remaining bug before meerging the pull-request, when you enable switch instead of text, it flickers on the lightswitches screen when you click on it. On the dashboard, it works as expected.

**Comment by davidlb** [comment]
Fixed, let's merge!

**Comment by DewGew** [comment]
How do i reset my setting? I have old settings in localStorage

**Comment by davidlb** [comment]
You need to clear application cache on your browser.

**Comment by DewGew** [comment]
Not a simple way on safari on iPhone thou. Alot of clicking. Now I have to reset all my cache on my Phone

**Pull request merged**
