### PR TITLE
Table background color

### PR DESCRIPTION
**Pull request by DewGew**
Change tables background color
#168

### CODE REVIEW

**Comment by landaisbenj** [comment]
it's missing border

**Comment by DewGew** [comment]
On the left and right or on the top?

**Comment by landaisbenj** [comment]
Everywere lol i have this : 
image

**Comment by DewGew** [comment]
Looks great

**Comment by landaisbenj** [comment]
Yes I forgot this.

**Comment by EdddieN** [comment]
I get something very different on the dark theme, maybe related to https://github.com/EdddieN/machinon-domoticz_theme/pull/171 ?

screenshot 2018-11-11 at 10 40 47

**Comment by DewGew** [comment]
Borders in tables in dark theme is fixed in latetst beta

**Comment by landaisbenj** [comment]
always problem with border color... We can't make them white.

**Comment by landaisbenj** [comment]
Hm i don't see the post ... You go too fast for me :(

**Comment by landaisbenj** [comment]
I've just make some change for white theme... More than zeplin on my last branch

**Pull request merged**
