### PR TITLE
Notify secstatus

### PR DESCRIPTION
**Pull request by DewGew**
With this you get a notification if security status changes..

### CODE REVIEW

**Comment by landaisbenj** [comment]
Can we have a noty on all notification ? Like a device have notification ON, maybe your stuff can history this too...

**Comment by DewGew** [comment]
Why, there is no need we have the log for this.. But its possible :)

**Comment by landaisbenj** [comment]
interactivity... theme more alive ... like all other domotic application. In the way of a controle tab where prevent all of change...

**Comment by landaisbenj** [comment]
Or maybe make an api ? for script ...... If i make a tab on wall. Maybe i want make a sound and noty on my door contact.... If i heard sound, i can view in live what is this.. Or open noty to know..

**Comment by EdddieN** [comment]
I think I know what landaisbenj means. Actually is not a bad idea...

Basically is some kind of log file. Obviously we have the log screen which is fine and debugs a lot of info. 

What if we have next to the bell icons a small "text" zone that was scrolling only the latest changes with no log. For example visualise this:

Kitchen motion ON 🔔 
.
. few seconds it clears alone, it only happens when you have the UI open
... nothing, emptly.... 🔔 
.
.
.
Kitchen door closed 🔔 
.
.
Kitchen motion OFF 🔔 

So we have like a small tiny window for status changes only that keeps scrolling automatically, and then we have the notifications for more system things. 

If this is what you mean, let me know and I can think of a why to tie it into the design, although that should not stop you from experimenting 😎

**Comment by landaisbenj** [comment]
O fuckin yes. It's exactly what I mean. Some status scrolling just when it does. Like an iPhone notification maybe or a flash alert on h24 info news. Replace by the new next status but reg on noty for some times.

**Comment by DewGew** [comment]
On dashticz I made a similar function. With speak, sound and/or text in lower bottom.

**Comment by landaisbenj** [comment]
And you tell me we don't needed this ... 
I think a tiny sound is good. Like a small bell.

**Pull request merged**
