### PR TITLE
Fix font size on temperatures, weather and utillity

### PR DESCRIPTION
**Pull request by DewGew**

### CODE REVIEW

**Comment by EdddieN** [comment]
mmm.. which font are you using? Shoudn't be OpenSans-Semibold 16px or so?
Do you have access to Zeplin? I may have miss-understood your question about font.

This is what I see which breaks the design a bit
screen shot 2018-08-30 at 21 04 39

**Comment by EdddieN** [comment]
This is what it is in Zeplin
screen shot 2018-08-30 at 21 05 25

**Comment by DewGew** [comment]
I only change the size

**Comment by DewGew** [comment]
I usually do like this:
Hit F12 the right click on refresh button.


clearcache

**Comment by EdddieN** [comment]
Interesting... my font is very different to yours on the tiles

**Comment by DewGew** [comment]
with mydomoticz I had to clear application cache to refresh my fonts and images.

**Comment by landaisbenj** [comment]
Yes me too.

**Comment by EdddieN** [comment]
Ok, I need to keep trying... forced clear cache (app too) but still loading old fonts on all my browsers. Anyway, is good it is right on your end :D

**Pull request merged**
