### PR TITLE
Update custom.css

### PR DESCRIPTION
**Pull request by landaisbenj**
@EdddieN can you review ?

### CODE REVIEW

**Comment by landaisbenj** [comment]
I push the branch

**Comment by DewGew** [comment]
There is alot of dom errors in the console log. offline, status tiles dont work in dashboard, temperatures and weather

**Comment by landaisbenj** [comment]
Ok i will look at console. But can you print the problem for status tile?

**Comment by DewGew** [comment]
dosent show if device is offline..

**Comment by landaisbenj** [comment]
Ok easy i look at that. 

Btw you must to tell me how you find all bug so quickly like that xD I don't know how to do.

**Comment by DewGew** [comment]
hit F12 in chrome

**Comment by EdddieN** [comment]
Ok, lots better!
Even floorplan works now well

the only thing remaining is this one, but this is an old challenge correct?
screenshot 2018-10-19 at 09 19 52

**Comment by landaisbenj** [comment]
> hit F12 in chrome then console

Yes but how do you know something like: Offline, low batt, protected status tiles dont work in dashboard, temperatures and weather

**Comment by landaisbenj** [comment]
> Ok, lots better!
> Even floorplan works now well
> 
> the only thing remaining is this one, but this is an old challenge correct?
> screenshot 2018-10-19 at 09 19 52

Yes. Either til grow up alone, or tile miss aligned. I search a lot for better solution.

**Comment by landaisbenj** [comment]
> There is alot of dom errors in the console log. Offline, low batt, protected status tiles dont work in dashboard, temperatures and weather

Ok for status in new beta. But for font i do not have probleme on v70 of google. And on firefox v 62
image

**Comment by landaisbenj** [comment]
> There is alot of dom errors in the console log. Offline, low batt, protected status tiles dont work in dashboard, temperatures and weather

Can you post dom error ? i do not have to. Just on thing on weather and temp tab. I'm on this. (bug without refresh...)

**Comment by DewGew** [comment]
Seems to be good now

**Pull request merged**
