### PR TITLE
Update custom.css

### PR DESCRIPTION
**Pull request by landaisbenj**
@DewGew I modify all to make .item flexible and no .span4. I think it could be fix all border color bug. But i don't know how to testing different status on dashboard or weather or other... Can you review, tell me if border work on all tile, and if color seems to be good ? I just change selector on custom.css no color...

### CODE REVIEW

**Comment by DewGew** [comment]
colors around tiles are working.  but now the tiles are aligned in dashboard, temperatures and weather like in switches and utilities

**Comment by landaisbenj** [comment]
"but" ? Give me a screen please.

**Comment by landaisbenj** [comment]
Ok so tile on dashboard, temp and weather are div with class span4 with child for item and on light, scene and utility tile are div with class span4 AND item and with child without item  ..??§!!?? Really fuckin code... I look at that.

**Comment by EdddieN** [comment]
On Chrome works really well now

**Comment by landaisbenj** [comment]
note to myself: 
```
div.item > section{
  position: relative;
  width: 20em !important;
  height: 10em !important;
  margin:20px 20px !important;
  flex-grow: 1;
  
  background: var(--main-item-bg-color);
  padding: 20px;
  border-radius: 6px;
  box-shadow: 0px 0px 10px 2px rgba(0, 0, 0, 0.2);

	
}


.span4:not(.item) {
	width:auto !important;
	height:auto !important;
	margin:0 !important;
	padding:0 !important;	
}

div.item .span4{
	width:auto !important;
	height:auto !important;
	margin:0 !important;
	padding:0 !important;

}
```

**Comment by DewGew** [comment]
@landaisbenj how is going? Do you find any workaround?

**Comment by landaisbenj** [comment]
I think i'm on a good way. With:
```
div.row .span4 table{
  position: relative;
  width: 20em !important;
  height: 10em !important;
  margin:20px 20px !important;
  flex-grow: 1;
  
  background: var(--main-item-bg-color);
  padding: 20px;
  border-radius: 6px;
  box-shadow: 0px 0px 10px 2px rgba(0, 0, 0, 0.2);
}
```
Who seem to be unique.

We must to suppress this:

```
body table#itemtable {
  /width: auto !important;
}
```

And think tile for all (border color, shadowbox etc, etc...) is :
```
div.row .span4 table{
```
I think we must have to replace all div.item by this...

I can do the change here. but i need more time to all colateral change.

**Comment by landaisbenj** [comment]
I think the branch is good. I need few time to make it more flex and more center. but i have a base now for all page, the tile are this :
`div.row .span4 table{`

**Comment by landaisbenj** [comment]
ntm: Maybe i need to view want can i do with this selector 
`[id*="item"]`

**Comment by landaisbenj** [comment]
@DewGew i want to suppress all class .span4 on div.row .divider and replace it by class "tile". 
I do that by :

`$("#main-view div.row.divider .span4").toggleClass('span4 tile')`

But if page refresh alone, this rollback my change. It's the question i posed before, how can i apply this jquery even it's refreshing ?

**Comment by landaisbenj** [comment]
I place it on my observer...
I've created test branch. I suppress span4 of all .item. span4 is for bootstrap to make 3 tile by row... So i think we don't need this. 
On suppress span 4 .item become the only container for tile. And so don't make collateral bug for flex. I can start work from that. I suppress all my branch to fork project on my board. Because i think we may have now a good beta.
I will work on dom to clean evrything who don't needed.

**Comment by landaisbenj** [comment]
Please look at that. Merge on beta. And tell me if you have some visual bug. I don't see big bug on chrome or firefox but i don't test on mobile/safari/edge/opera etc...

**Comment by landaisbenj** [comment]
Ok i look at that. But for floorplan i think i need time.

**Pull request merged**
