### PR TITLE
Support new websocket version of Domoticz

### PR DESCRIPTION
**Pull request by davidlb**
To be tested

### CODE REVIEW

**Comment by DewGew** [comment]
Time ago does not update correct:

time_update

**Comment by davidlb** [comment]
@DewGew , do you have any error in the console?

**Comment by davidlb** [comment]
Migration to websockets is mostly done, I just don't get how to catch websocket response for scenes (for the switch instead of text feature)

**Comment by davidlb** [comment]
Finally ready for merging!

But there is a major rewrite of the javascript of Domoticz to a new version of Angular that will probably broke everything once again...

**Pull request merged**
