### PR TITLE
Minor cosmectics

### PR DESCRIPTION
**Pull request by davidlb**
- Add more space between grids and titles
- Add little margin on both side for tablet screens

### CODE REVIEW

**Comment by davidlb** [comment]
Forgot to push 2 commits when creating PR:
* Better look for the menu button on tablet
* Override main font on body for better consistency

**Comment by davidlb** [comment]
Here is a screenshot after fixes
2019-03-20 17_03_46-Window

**Comment by DewGew** [comment]
I moved mobile css to css/mobile.css. For easier reading. You have to resolve this first.

**Comment by DewGew** [comment]
Thanks 👍

**Pull request merged**
