### PR TITLE
Status autoscroll

### PR DESCRIPTION
**Pull request by davidlb**
- Set autoscroll for long status
- Remove nanoscroller

### CODE REVIEW

**Comment by landaisbenj** [comment]
I think it broken clean status. On beta we have all line on new line (much pretty) :

image

and now, all status 

take an old display

image

**Comment by davidlb** [comment]
Good catch, thanks :)
Last commit fix it!

**Comment by landaisbenj** [comment]
Ok beautifull. But in my opinion i think my transition is better because everytime you have text status on eye...

**Comment by davidlb** [comment]
Previous scroll :)

**Comment by landaisbenj** [comment]
Any reason to start and backup translation to 10px ? It make a visual gap on scrolling...

**Comment by davidlb** [comment]
IN a way you're right but otherwise the first line disappears too quickly

**Comment by landaisbenj** [comment]
hmm ok maybe we can do something with translation. Maybe in make de translation pause before... i saw that

**Comment by landaisbenj** [comment]
If we add a transition i think it's good:

```
@keyframes autoscroll {
    0%   { 
        transform: translateY(0);
    }
    10%   { 
        transform: translateY(0);
    }
    90% { 
        transform: translateY(-50%);
    }
    100%   { 
        transform: translateY(0);
    }
}
```

**Comment by davidlb** [comment]
Yeash, it's good now!

**Comment by landaisbenj** [comment]
Géniale !

**Pull request merged**
