### PR TITLE
Device timeout

### PR DESCRIPTION
**Pull request by DewGew**
When a device is timed out. It fades out.

default theme:
timeout_default
machinon theme:
timeout_machinon

### CODE REVIEW

**Comment by EdddieN** [comment]
Can we have the fade out with the red outline?

**Comment by DewGew** [comment]
Sure.. a little bit a both :)
Maybe we can have similair to protected devices and battery low ? Maybe not fade out but a faded border ?

**Comment by landaisbenj** [comment]
Animation idea here:
https://github.com/EdddieN/machinon-domoticz_theme/issues/29#issuecomment-411026272

**Comment by EdddieN** [comment]
Yes, the thing is very "alarming" visual is that they are ver alarming to start and then they become very normal over time so when something important needs attention... we got so used to it that we ignore it. 

For the battery, I like the idea, do you get detail information on battery level per device? or just a getting empty? On my installation I only get alerts when they are about 10% left. But if we have a gradual 0 to 10%, then we could do something like this, very subtle 
screen shot 2018-08-29 at 18 15 08

**Pull request merged**
