### PR TITLE
Cleanup and fixes

### PR DESCRIPTION
**Pull request by davidlb**

### CODE REVIEW

**Comment by DewGew** [comment]
Great work

**Comment by EdddieN** [comment]
Updates faster than I can test them 😆 Really nice!

**Comment by davidlb** [comment]
Thanks :)
I had free time last week so I decided to work on this amazing theme.
What do you think about merging to master? But before, icon WindNW.png is still missing and I don't know where to get it.

**Comment by DewGew** [comment]
I Will fix the icon tomorrow. I request for new master

**Comment by DewGew** [comment]
WindNW icons is uploaded

**Pull request merged**
