### PR TITLE
Add option to display camera preview on dashboard (enabled by default)

### PR DESCRIPTION
**Pull request by davidlb**
To use it:
- You need to attach a switch to your camera (create a switch then in Settings/Camera, add the switch to the camera)
-  Add the switch to the dashboard

Result:
2019-04-19 15_10_06-Lyon – Brave

### CODE REVIEW

**Comment by EdddieN** [comment]
I'm seriously impressed!!

**Comment by DewGew** [comment]
👍

**Comment by EdddieN** [comment]
I do not seem to get the image to appear on the tile. Switch is linked and when I click on the camera icon on the tile switch it loads the pop up with the image but not on the tile

**Comment by davidlb** [comment]
It only works on the dashboard. But I have a much better idea now to avoid the switch trick. I'll code it on Tuesday :)

**Comment by EdddieN** [comment]
Sorry, wrong screenshot. Not sure what I was thinking and why I added the switch. 

See attached, @DewGew is working for you ok? Just trying to make sure it is now a cache issue on my side.
Screenshot 2019-04-21 at 12 55 59

**Comment by davidlb** [comment]
Do you see the option in the theme settings? It looks like a cache problem.

**Comment by EdddieN** [comment]
Completely missed that option under settings! Works great now, thank you!

**Pull request merged**
