### PR TITLE
Typo and Rewrite

### PR DESCRIPTION
**Pull request by DewGew**
Edited @landaisbenj functions for better owerview in custom.js
Moved other functions to functions.js

### CODE REVIEW

**Comment by EdddieN** [comment]
Works for me now! 

Visually this is what I get, correct?
screen shot 2018-09-04 at 08 55 59

**Comment by DewGew** [comment]
Yes. To bad the tiles won't move to top when searching

**Comment by landaisbenj** [comment]
This is normal ? Maybe it's flex ?

**Comment by landaisbenj** [comment]
And it's hide bannav and table[0] brother of lightcontent. Maybe you can change that for filter just content children...

**Comment by landaisbenj** [comment]
If i just inspect a tile code and i add 'display="none" the tile is still there. But if i add just "hidden", tile disapear and other move.

**Comment by EdddieN** [comment]
well... sound like a way towards the solution at least :D

**Comment by landaisbenj** [comment]
Ok i find how to move item 

```
function searchFunction() {
	if ($('#dashcontent') || $('lightcontent') || $('scenecontent')|| $('utilitycontent') || $('weatherwidgets') || $('tempwidgets')){
		var value = $('#searchInput').val().toLowerCase();
		$("div .item").filter(function() {
		  $(this).toggle($(this).find('#name').html().toLowerCase().indexOf(value) > -1)
		});
    };
};
```

i make a pull

**Pull request merged**
