### PR TITLE
Fix for Edge

### PR DESCRIPTION
**Pull request by DewGew**
Fix for Timer and Log icons to work with Edge.
Added missing Temperature log Icons

### CODE REVIEW

**Comment by EdddieN** [comment]
@sweetpants can you confirm is working for you?

**Comment by sweetpants** [comment]
Yep, last update fixed my dashboard issue. Looking nice now

**Comment by sweetpants** [comment]
Like the new 'show log' button, except this is not present with temperature sensors (yet)

**Comment by DewGew** [comment]
Temp log icon should be there now. Download latest from today

**Pull request merged**
