### PR TITLE
Dew gew simplenoty

### PR DESCRIPTION
**Pull request by DewGew**
Simple notification, only works with check new update for now..

dashboard

### CODE REVIEW

**Comment by EdddieN** [comment]
Brilliant! I guess I need to wait for the next update to see the notification there

**Comment by landaisbenj** [comment]
I don't know why but noty display me a update for domoticz... But i'm on stable version... No update since june

**Comment by DewGew** [comment]
Ok, I check this..

**Comment by DewGew** [comment]
> I don't know why but noty display me a update for domoticz... But i'm on stable version... No update since june

Fixed in latest beta

**Comment by landaisbenj** [comment]
👍

**Comment by landaisbenj** [comment]
Bell must not stay even without noty ?

**Comment by landaisbenj** [comment]
And for more lively maybe notification of domoticz can be integrate ? All tile with notification can add their notification in it ...

**Pull request merged**
